name: Build Push Fedora related containers

on: [push]

permissions: write-all

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-os:
    runs-on: ubuntu-latest
    container:
      image: quay.io/buildah/stable:latest
      options: --privileged
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to ghcr.io
        run: buildah login -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }} ${{ env.IMAGE_REGISTRY }}
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_REGISTRY }}/os
          tags: 39
          context: ./os
          containerfiles: |
            ./os/Dockerfile
          layers: true
          oci: true
          extra-args: |
            --cache-from ${{ env.IMAGE_REGISTRY }}/os
            --cache-to ${{ env.IMAGE_REGISTRY }}/os
      - name: Push image
        run: buildah push ${{ env.IMAGE_REGISTRY }}/os:39
  build-toolbox:
    runs-on: ubuntu-latest
    container:
      image: quay.io/buildah/stable:latest
      options: --privileged
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to ghcr.io
        run: buildah login -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }} ${{ env.IMAGE_REGISTRY }}
      - name: Cleanup github action runner disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_REGISTRY }}/toolbox
          tags: 39
          context: ./toolbox
          containerfiles: |
            ./toolbox/Dockerfile
          layers: true
          oci: true
          extra-args: |
            --cache-from ${{ env.IMAGE_REGISTRY }}/toolbox
            --cache-to ${{ env.IMAGE_REGISTRY }}/toolbox
      - name: Push image
        run: buildah push ${{ env.IMAGE_REGISTRY }}/toolbox:39
